### PR TITLE
Update jquery-watch.js

### PR DESCRIPTION
**Pull request by horch004**
I edited the script to include handling of the $(...).prop(...) function.

Changed the __watcher function to call the callback for each change detected. The previous/original script stops at the first change detected.

### CODE REVIEW

**Comment by RickStrahl** [comment]
Have you tried this out with .props(). 

Some time ago I experimented with "props_" syntax, but I had all sorts of problems with the property changes not being detected, so I pulled it. I think it works in some browsers but even in evergreen it seems inconsistent.

**Comment by RickStrahl** [comment]
*Changed the __watcher function to call the callback for each change detected. The previous/original script stops at the first change detected.*

Hmmm... I'm not sure that you'd want this because the callback gives you the element that has changed. If more than one thing changed you're essentially getting the same information more than once resulting in what will feel like multiple events for the same thing.

Could you give a use case where multiple calls for each changed property in a single call makes sense?

**Comment by horch004** [comment]
Hi Rick,
I'm also a VFP + web programmer. Surprisingly, you show up quite a number of times in Google when I search for things (thumb). 

1) The jQuery doc http://api.jquery.com/prop/ has a Attributes vs. Properties heading. Some properties can be better pulled using the prop method instead of the attr method. An example given is the 'checked' property of a checkbox.
I thought I needed the prop syntax, but it turned out I had to use the attr syntax... duhhh...
So, it's your call to leave it as is or not.

2) The __watcher function scans the list of attributes/properties to find the changes. If the function stops at the first change found. I would have to scan for myself again in the callback to find the other changes. 
To be honest, I thought I had a case. That's why I changed the function. But... while working on the case it turned out it could be done just how it is now. So, nope... no case, below is just a thought.
In the proposed change to the watcher function the callback can change an attribute or property on the element which is also tracked and then the watcher function detects that change and calls the callback function again to handle that change. This might be ok, but the function could also first detect all changes and then call the callback ones with an array of changed indexes or somehow.

In the end you can just leave it as it is. Thanks for sharing the code.

**Comment by RickStrahl** [comment]
Re: Props(). The issue with $.prop() is that `MutationObserver` does not monitor property changes - it only monitors attribute changes or attribute changes to property values. So in some cases (where properties are modified through attributes) you get change notifications and in others (when properties are changed in code) you won't get notifications. So it's very inconsistent and not reliable.

**Comment by horch004** [comment]
Thanks for the information and your time on this.

**Pull request closed without merging**
